# Generated by Django 5.0.3 on 2024-04-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
