# Generated by Django 5.0.3 on 2024-04-04 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='chatHistory',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='number_of_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='chatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('chatLog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatMessages', to='controller_app.chathistory')),
            ],
        ),
    ]
