# Generated by Django 5.0.3 on 2024-04-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller_app', '0002_chatmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
