# Generated by Django 5.0.3 on 2024-04-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller_app', '0002_chatmessage_message_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='message_num',
        ),
    ]
